// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameConfig = "config"

// Config mapped from table <config>
type Config struct {
	Secretaries       string    `gorm:"column:secretaries" json:"secretaries"`
	PreferredNames    string    `gorm:"column:preferredNames" json:"preferredNames"`
	ExcludedTeachers  string    `gorm:"column:excludedTeachers" json:"excludedTeachers"`
	SemesterClassName string    `gorm:"column:semesterClassName" json:"semesterClassName"`
	IsRedisCluster    bool      `gorm:"column:isRedisCluster;default:true" json:"isRedisCluster"`
	CreatedAt         time.Time `gorm:"column:createdAt;primaryKey;default:now()" json:"createdAt"`
}

// TableName Config's table name
func (*Config) TableName() string {
	return TableNameConfig
}
