// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSession = "session"

// Session mapped from table <session>
type Session struct {
	SessionToken string    `gorm:"column:sessionToken;primaryKey" json:"sessionToken"`
	UserID       string    `gorm:"column:userId;not null" json:"userId"`
	Expires      time.Time `gorm:"column:expires;not null" json:"expires"`
}

// TableName Session's table name
func (*Session) TableName() string {
	return TableNameSession
}
