// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID            string    `gorm:"column:id;primaryKey" json:"id"`
	Name          string    `gorm:"column:name" json:"name"`
	Email         string    `gorm:"column:email;not null" json:"email"`
	EmailVerified time.Time `gorm:"column:emailVerified" json:"emailVerified"`
	Image         string    `gorm:"column:image" json:"image"`
	Role          string    `gorm:"column:role;not null;default:student" json:"role"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
