// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAvailability = "availability"

// Availability mapped from table <availability>
type Availability struct {
	ID          string    `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ClassroomID string    `gorm:"column:classroomId;not null" json:"classroomId"`
	Date        time.Time `gorm:"column:date;not null" json:"date"`
	Available   bool      `gorm:"column:available;not null" json:"available"`
	TeacherID   string    `gorm:"column:teacherId" json:"teacherId"`
}

// TableName Availability's table name
func (*Availability) TableName() string {
	return TableNameAvailability
}
