// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRequest = "requests"

// Request mapped from table <requests>
type Request struct {
	ID                 int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	StudentID          string    `gorm:"column:studentId;not null" json:"studentId"`
	StudentName        string    `gorm:"column:studentName;not null" json:"studentName"`
	NewTeacher         string    `gorm:"column:newTeacher;not null" json:"newTeacher"`
	NewTeacherName     string    `gorm:"column:newTeacherName;not null" json:"newTeacherName"`
	CurrentTeacher     string    `gorm:"column:currentTeacher;not null" json:"currentTeacher"`
	CurrentTeacherName string    `gorm:"column:currentTeacherName;not null" json:"currentTeacherName"`
	DateRequested      time.Time `gorm:"column:dateRequested;not null" json:"dateRequested"`
	Status             string    `gorm:"column:status;not null;default:pending" json:"status"`
	Arrived            bool      `gorm:"column:arrived" json:"arrived"`
	Timestamp          string    `gorm:"column:timestamp;not null" json:"timestamp"`
}

// TableName Request's table name
func (*Request) TableName() string {
	return TableNameRequest
}
