basePath: /
host: localhost:6969
info:
  contact: {}
  description: This is the API for the Laurel Public Schools
  title: LPS API
  version: "1.0"
paths: {}
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
