basePath: /api
definitions:
  utils.Error:
    properties:
      errors:
        additionalProperties: true
        type: object
    type: object
host: localhost:6969
info:
  contact: {}
  description: This is the API for the Laurel Public Schools
  title: LPS API
  version: "1.0"
paths:
  /email:
    post:
      consumes:
      - application/json
      description: Send an email via post request
      operationId: send-email
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: Send an email
      tags:
      - email
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
